name: Build and push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install --prefix services/monarch-ui
      - run: npm run build
      - run: docker build .
        if: github.ref != 'refs/heads/master'
      - uses: elgohr/Publish-Docker-Github-Action@master
        if: github.ref == 'refs/heads/master'
        with:
          name: simonschneider/monarch
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
