export const LOAD_CONFIG = "LOAD_CONFIG";
export const LOADING_CONFIG = "LOADING_CONFIG";
export const LOAD_BACKEND_CONFIG = "LOAD_BACKEND_CONFIG";
export const LOADING_BACKEND_CONFIG = "LOADING_BACKEND_CONFIG";
